// Real-world seed catalog — accurate authors, series, and 50 books.
// Each schema genre appears on at least 5 books.

export const authorsData = [
  { key: "meyer", name: "Stephenie Meyer", bio: "American novelist best known for the Twilight series.", profileImage: "https://covers.openlibrary.org/a/olid/OL1394365A-M.jpg" },
  { key: "rowling", name: "J.K. Rowling", bio: "British author of the Harry Potter series.", profileImage: "https://covers.openlibrary.org/a/olid/OL23919A-M.jpg" },
  { key: "collins", name: "Suzanne Collins", bio: "American writer of The Hunger Games trilogy.", profileImage: "https://covers.openlibrary.org/a/olid/OL1391148A-M.jpg" },
  { key: "martin", name: "George R.R. Martin", bio: "American novelist and creator of A Song of Ice and Fire.", profileImage: "https://covers.openlibrary.org/a/olid/OL26759A-M.jpg" },
  { key: "tolkien", name: "J.R.R. Tolkien", bio: "English writer and author of The Lord of the Rings.", profileImage: "https://covers.openlibrary.org/a/olid/OL26320A-M.jpg" },
  { key: "king", name: "Stephen King", bio: "American author of horror, suspense, and fantasy.", profileImage: "https://covers.openlibrary.org/a/olid/OL2162284A-M.jpg" },
  { key: "christie", name: "Agatha Christie", bio: "English writer known for detective novels.", profileImage: "https://covers.openlibrary.org/a/olid/OL20699A-M.jpg" },
  { key: "michaelides", name: "Alex Michaelides", bio: "Cypriot-British author of The Silent Patient.", profileImage: "https://placehold.co/200x200?text=Alex+Michaelides" },
  { key: "hawking", name: "Stephen Hawking", bio: "Theoretical physicist and science communicator.", profileImage: "https://covers.openlibrary.org/a/olid/OL2621816A-M.jpg" },
  { key: "frank", name: "Anne Frank", bio: "Jewish diarist whose wartime journal became a classic.", profileImage: "https://covers.openlibrary.org/a/olid/OL26336A-M.jpg" },
  { key: "obama", name: "Michelle Obama", bio: "Author and former First Lady of the United States.", profileImage: "https://placehold.co/200x200?text=Michelle+Obama" },
  { key: "clear", name: "James Clear", bio: "Writer on habits and continuous improvement.", profileImage: "https://placehold.co/200x200?text=James+Clear" },
  { key: "kaling", name: "Mindy Kaling", bio: "Actress, comedian, and memoirist.", profileImage: "https://placehold.co/200x200?text=Mindy+Kaling" },
  { key: "fey", name: "Tina Fey", bio: "Comedian, writer, and author of Bossypants.", profileImage: "https://placehold.co/200x200?text=Tina+Fey" },
  { key: "kiyosaki", name: "Robert Kiyosaki", bio: "Entrepreneur and author of Rich Dad Poor Dad.", profileImage: "https://placehold.co/200x200?text=Robert+Kiyosaki" },
  { key: "isaacson", name: "Walter Isaacson", bio: "Biographer of Steve Jobs, Einstein, and others.", profileImage: "https://placehold.co/200x200?text=Walter+Isaacson" },
  { key: "hawkins", name: "Paula Hawkins", bio: "British author of The Girl on the Train.", profileImage: "https://placehold.co/200x200?text=Paula+Hawkins" },
  { key: "crichton", name: "Michael Crichton", bio: "Author of techno-thrillers including Jurassic Park.", profileImage: "https://covers.openlibrary.org/a/olid/OL2632305A-M.jpg" },
  { key: "orwell", name: "George Orwell", bio: "English novelist and essayist.", profileImage: "https://covers.openlibrary.org/a/olid/OL118415A-M.jpg" },
  { key: "lee", name: "Harper Lee", bio: "American novelist, author of To Kill a Mockingbird.", profileImage: "https://covers.openlibrary.org/a/olid/OL23919A-M.jpg" },
  { key: "austen", name: "Jane Austen", bio: "English novelist known for Pride and Prejudice.", profileImage: "https://covers.openlibrary.org/a/olid/OL21584A-M.jpg" },
  { key: "bronte", name: "Charlotte Brontë", bio: "English novelist, author of Jane Eyre.", profileImage: "https://covers.openlibrary.org/a/olid/OL21570A-M.jpg" },
  { key: "dahl", name: "Roald Dahl", bio: "British author of beloved children's books.", profileImage: "https://covers.openlibrary.org/a/olid/OL34184A-M.jpg" },
  { key: "seuss", name: "Dr. Seuss", bio: "American children's author and illustrator.", profileImage: "https://covers.openlibrary.org/a/olid/OL23919A-M.jpg" },
  { key: "asimov", name: "Isaac Asimov", bio: "Prolific science-fiction writer.", profileImage: "https://covers.openlibrary.org/a/olid/OL34221A-M.jpg" },
  { key: "herbert", name: "Frank Herbert", bio: "Author of the Dune saga.", profileImage: "https://covers.openlibrary.org/a/olid/OL26289A-M.jpg" },
  { key: "flynn", name: "Gillian Flynn", bio: "American author of psychological thrillers.", profileImage: "https://placehold.co/200x200?text=Gillian+Flynn" },
  { key: "harris", name: "Thomas Harris", bio: "Author of The Silence of the Lambs.", profileImage: "https://placehold.co/200x200?text=Thomas+Harris" },
  { key: "brown", name: "Dan Brown", bio: "Author of The Da Vinci Code and related thrillers.", profileImage: "https://covers.openlibrary.org/a/olid/OL34212A-M.jpg" },
  { key: "mandel", name: "Emily St. John Mandel", bio: "Canadian novelist, author of Station Eleven.", profileImage: "https://placehold.co/200x200?text=Emily+Mandel" },
  { key: "atwood", name: "Margaret Atwood", bio: "Canadian poet and novelist.", profileImage: "https://covers.openlibrary.org/a/olid/OL22815A-M.jpg" },
  { key: "gaiman", name: "Neil Gaiman", bio: "Author of fantasy and speculative fiction.", profileImage: "https://covers.openlibrary.org/a/olid/OL27294A-M.jpg" },
  { key: "lewis", name: "C.S. Lewis", bio: "Author of The Chronicles of Narnia.", profileImage: "https://covers.openlibrary.org/a/olid/OL22098A-M.jpg" },
  { key: "riordan", name: "Rick Riordan", bio: "Author of Percy Jackson & the Olympians.", profileImage: "https://placehold.co/200x200?text=Rick+Riordan" },
  { key: "gladwell", name: "Malcolm Gladwell", bio: "Journalist and author of business and social science bestsellers.", profileImage: "https://placehold.co/200x200?text=Malcolm+Gladwell" },
];

export const seriesData = [
  { key: "twilight", title: "Twilight Saga" },
  { key: "harry-potter", title: "Harry Potter" },
  { key: "hunger-games", title: "The Hunger Games" },
  { key: "asoiaf", title: "A Song of Ice and Fire" },
  { key: "lotr", title: "The Lord of the Rings" },
  { key: "narnia", title: "The Chronicles of Narnia" },
  { key: "dune", title: "Dune" },
  { key: "percy", title: "Percy Jackson & the Olympians" },
  { key: "foundation", title: "Foundation" },
];

export const booksData = [
  { key: "twilight", title: "Twilight", authorKey: "meyer", seriesKey: "twilight", description: "Bella Swan moves to Forks and falls in love with mysterious vampire Edward Cullen.", genres: ["romance", "young-adult", "fantasy"], coverImage: "https://covers.openlibrary.org/b/isbn/9780316015844-L.jpg", language: "english", totalChapters: 12, publishedAt: "2005-10-05", averageRating: 4.2, ratingsCount: 5200000, popularityScore: 98 },
  { key: "new-moon", title: "New Moon", authorKey: "meyer", seriesKey: "twilight", description: "Edward leaves Bella, and she finds comfort with werewolf Jacob Black.", genres: ["romance", "young-adult", "fantasy"], coverImage: "https://covers.openlibrary.org/b/isbn/9780316160193-L.jpg", language: "english", totalChapters: 12, publishedAt: "2006-09-06", averageRating: 4.0, ratingsCount: 4100000, popularityScore: 94 },
  { key: "eclipse", title: "Eclipse", authorKey: "meyer", seriesKey: "twilight", description: "Bella must choose between Edward and Jacob as a vampire army threatens Forks.", genres: ["romance", "young-adult", "action"], coverImage: "https://covers.openlibrary.org/b/isbn/9780316160209-L.jpg", language: "english", totalChapters: 12, publishedAt: "2007-08-07", averageRating: 4.1, ratingsCount: 3900000, popularityScore: 93 },

  { key: "hp1", title: "Harry Potter and the Sorcerer's Stone", authorKey: "rowling", seriesKey: "harry-potter", description: "An orphaned boy discovers he is a wizard and begins his education at Hogwarts.", genres: ["fantasy", "children", "adventure"], coverImage: "https://covers.openlibrary.org/b/isbn/9780590353427-L.jpg", language: "english", totalChapters: 12, publishedAt: "1997-06-26", averageRating: 4.7, ratingsCount: 9000000, popularityScore: 100 },
  { key: "hp2", title: "Harry Potter and the Chamber of Secrets", authorKey: "rowling", seriesKey: "harry-potter", description: "Harry returns to Hogwarts and faces a monster hidden in the Chamber of Secrets.", genres: ["fantasy", "children", "mystery"], coverImage: "https://covers.openlibrary.org/b/isbn/9780439064873-L.jpg", language: "english", totalChapters: 12, publishedAt: "1998-07-02", averageRating: 4.6, ratingsCount: 8500000, popularityScore: 97 },
  { key: "hp3", title: "Harry Potter and the Prisoner of Azkaban", authorKey: "rowling", seriesKey: "harry-potter", description: "Harry learns the truth about Sirius Black and confronts the past.", genres: ["fantasy", "young-adult", "adventure"], coverImage: "https://covers.openlibrary.org/b/isbn/9780439136365-L.jpg", language: "english", totalChapters: 12, publishedAt: "1999-07-08", averageRating: 4.8, ratingsCount: 8200000, popularityScore: 99 },

  { key: "hg1", title: "The Hunger Games", authorKey: "collins", seriesKey: "hunger-games", description: "Katniss Everdeen volunteers for a televised fight to the death in dystopian Panem.", genres: ["young-adult", "action", "science-fiction"], coverImage: "https://covers.openlibrary.org/b/isbn/9780439023481-L.jpg", language: "english", totalChapters: 12, publishedAt: "2008-09-14", averageRating: 4.4, ratingsCount: 7500000, popularityScore: 96 },
  { key: "hg2", title: "Catching Fire", authorKey: "collins", seriesKey: "hunger-games", description: "Katniss and Peeta are forced back into the arena as rebellion stirs.", genres: ["young-adult", "action", "drama"], coverImage: "https://covers.openlibrary.org/b/isbn/9780439023498-L.jpg", language: "english", totalChapters: 12, publishedAt: "2009-09-01", averageRating: 4.5, ratingsCount: 6800000, popularityScore: 95 },

  { key: "got1", title: "A Game of Thrones", authorKey: "martin", seriesKey: "asoiaf", description: "Noble houses vie for the Iron Throne while an ancient threat rises in the north.", genres: ["fantasy", "drama", "adventure"], coverImage: "https://covers.openlibrary.org/b/isbn/9780553103540-L.jpg", language: "english", totalChapters: 12, publishedAt: "1996-08-01", averageRating: 4.6, ratingsCount: 2400000, popularityScore: 92 },
  { key: "fellowship", title: "The Fellowship of the Ring", authorKey: "tolkien", seriesKey: "lotr", description: "Frodo Baggins begins a quest to destroy the One Ring.", genres: ["fantasy", "adventure", "action"], coverImage: "https://covers.openlibrary.org/b/isbn/9780547928210-L.jpg", language: "english", totalChapters: 12, publishedAt: "1954-07-29", averageRating: 4.5, ratingsCount: 2800000, popularityScore: 94 },
  { key: "two-towers", title: "The Two Towers", authorKey: "tolkien", seriesKey: "lotr", description: "The Fellowship is broken as war spreads across Middle-earth.", genres: ["fantasy", "adventure", "action"], coverImage: "https://covers.openlibrary.org/b/isbn/9780547928203-L.jpg", language: "english", totalChapters: 12, publishedAt: "1954-11-11", averageRating: 4.5, ratingsCount: 2500000, popularityScore: 91 },
  { key: "narnia1", title: "The Lion, the Witch and the Wardrobe", authorKey: "lewis", seriesKey: "narnia", description: "Four siblings enter Narnia and join Aslan against the White Witch.", genres: ["fantasy", "children", "adventure"], coverImage: "https://covers.openlibrary.org/b/isbn/9780064471046-L.jpg", language: "english", totalChapters: 12, publishedAt: "1950-10-16", averageRating: 4.3, ratingsCount: 2600000, popularityScore: 90 },

  { key: "shining", title: "The Shining", authorKey: "king", seriesKey: null, description: "A family winters in an isolated hotel where supernatural forces drive the father mad.", genres: ["horror", "thriller", "drama"], coverImage: "https://covers.openlibrary.org/b/isbn/9780307743657-L.jpg", language: "english", totalChapters: 12, publishedAt: "1977-01-28", averageRating: 4.4, ratingsCount: 1400000, popularityScore: 89 },
  { key: "it", title: "It", authorKey: "king", seriesKey: null, description: "Children in Derry confront an ancient evil that returns every 27 years.", genres: ["horror", "fantasy", "thriller"], coverImage: "https://covers.openlibrary.org/b/isbn/9781501142970-L.jpg", language: "english", totalChapters: 12, publishedAt: "1986-09-15", averageRating: 4.3, ratingsCount: 1100000, popularityScore: 88 },
  { key: "pet-sematary", title: "Pet Sematary", authorKey: "king", seriesKey: null, description: "A burial ground behind a family's new home offers a terrible second chance.", genres: ["horror", "drama", "thriller"], coverImage: "https://covers.openlibrary.org/b/isbn/9781982115982-L.jpg", language: "english", totalChapters: 12, publishedAt: "1983-11-14", averageRating: 4.1, ratingsCount: 650000, popularityScore: 84 },
  { key: "carrie", title: "Carrie", authorKey: "king", seriesKey: null, description: "A bullied teenager unleashes telekinetic rage on her town.", genres: ["horror", "young-adult", "drama"], coverImage: "https://covers.openlibrary.org/b/isbn/9780307743671-L.jpg", language: "english", totalChapters: 10, publishedAt: "1974-04-05", averageRating: 4.0, ratingsCount: 700000, popularityScore: 83 },
  { key: "coral", title: "Coraline", authorKey: "gaiman", seriesKey: null, description: "A girl discovers a parallel world behind a door in her new flat.", genres: ["horror", "children", "fantasy"], coverImage: "https://covers.openlibrary.org/b/isbn/9780380807345-L.jpg", language: "english", totalChapters: 10, publishedAt: "2002-07-02", averageRating: 4.2, ratingsCount: 680000, popularityScore: 85 },

  { key: "orient", title: "Murder on the Orient Express", authorKey: "christie", seriesKey: null, description: "Hercule Poirot investigates a murder aboard a snowbound train.", genres: ["mystery", "crime", "thriller"], coverImage: "https://covers.openlibrary.org/b/isbn/9780062693662-L.jpg", language: "english", totalChapters: 12, publishedAt: "1934-01-01", averageRating: 4.3, ratingsCount: 1100000, popularityScore: 87 },
  { key: "none", title: "And Then There Were None", authorKey: "christie", seriesKey: null, description: "Ten strangers are invited to an island where they are killed one by one.", genres: ["mystery", "crime", "thriller"], coverImage: "https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg", language: "english", totalChapters: 12, publishedAt: "1939-11-06", averageRating: 4.4, ratingsCount: 1300000, popularityScore: 90 },
  { key: "ackroyd", title: "The Murder of Roger Ackroyd", authorKey: "christie", seriesKey: null, description: "Poirot comes out of retirement to solve a shocking village murder.", genres: ["mystery", "crime", "drama"], coverImage: "https://covers.openlibrary.org/b/isbn/9780007527526-L.jpg", language: "english", totalChapters: 12, publishedAt: "1926-06-01", averageRating: 4.3, ratingsCount: 420000, popularityScore: 82 },
  { key: "davinci", title: "The Da Vinci Code", authorKey: "brown", seriesKey: null, description: "A symbologist follows a trail of clues hidden in famous artworks.", genres: ["mystery", "thriller", "adventure"], coverImage: "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg", language: "english", totalChapters: 12, publishedAt: "2003-03-18", averageRating: 3.9, ratingsCount: 2300000, popularityScore: 91 },
  { key: "gone-girl", title: "Gone Girl", authorKey: "flynn", seriesKey: null, description: "A woman's disappearance exposes the dark side of a perfect marriage.", genres: ["mystery", "thriller", "drama"], coverImage: "https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg", language: "english", totalChapters: 12, publishedAt: "2012-06-05", averageRating: 4.1, ratingsCount: 2800000, popularityScore: 93 },

  { key: "silent-patient", title: "The Silent Patient", authorKey: "michaelides", seriesKey: null, description: "A famous painter shoots her husband and never speaks again—until a therapist tries to uncover why.", genres: ["thriller", "mystery", "crime"], coverImage: "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg", language: "english", totalChapters: 12, publishedAt: "2019-02-05", averageRating: 4.2, ratingsCount: 1800000, popularityScore: 95 },
  { key: "lambs", title: "The Silence of the Lambs", authorKey: "harris", seriesKey: null, description: "FBI trainee Clarice Starling seeks help from Hannibal Lecter to catch a serial killer.", genres: ["thriller", "crime", "horror"], coverImage: "https://covers.openlibrary.org/b/isbn/9780312924584-L.jpg", language: "english", totalChapters: 12, publishedAt: "1988-05-01", averageRating: 4.3, ratingsCount: 700000, popularityScore: 88 },
  { key: "jurassic", title: "Jurassic Park", authorKey: "crichton", seriesKey: null, description: "Scientists clone dinosaurs for a theme park that spirals out of control.", genres: ["thriller", "science-fiction", "action"], coverImage: "https://covers.openlibrary.org/b/isbn/9780345538987-L.jpg", language: "english", totalChapters: 12, publishedAt: "1990-11-01", averageRating: 4.2, ratingsCount: 980000, popularityScore: 90 },

  { key: "dune1", title: "Dune", authorKey: "herbert", seriesKey: "dune", description: "On the desert planet Arrakis, Paul Atreides is drawn into a struggle over spice and destiny.", genres: ["science-fiction", "adventure", "fantasy"], coverImage: "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg", language: "english", totalChapters: 12, publishedAt: "1965-08-01", averageRating: 4.3, ratingsCount: 1400000, popularityScore: 94 },
  { key: "foundation1", title: "Foundation", authorKey: "asimov", seriesKey: "foundation", description: "Hari Seldon's plan to shorten a galactic dark age begins on the edge of the Empire.", genres: ["science-fiction", "adventure", "drama"], coverImage: "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg", language: "english", totalChapters: 10, publishedAt: "1951-06-01", averageRating: 4.2, ratingsCount: 550000, popularityScore: 86 },
  { key: "1984", title: "1984", authorKey: "orwell", seriesKey: null, description: "Winston Smith rebels against a totalitarian regime that watches every move.", genres: ["science-fiction", "drama", "thriller"], coverImage: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg", language: "english", totalChapters: 12, publishedAt: "1949-06-08", averageRating: 4.2, ratingsCount: 4500000, popularityScore: 97 },
  { key: "handmaid", title: "The Handmaid's Tale", authorKey: "atwood", seriesKey: null, description: "In a theocratic dystopia, Offred navigates life as a Handmaid.", genres: ["science-fiction", "drama", "historical"], coverImage: "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg", language: "english", totalChapters: 12, publishedAt: "1985-08-01", averageRating: 4.1, ratingsCount: 1900000, popularityScore: 89 },
  { key: "station11", title: "Station Eleven", authorKey: "mandel", seriesKey: null, description: "A traveling Shakespeare troupe survives in a world after a devastating pandemic.", genres: ["science-fiction", "drama", "adventure"], coverImage: "https://covers.openlibrary.org/b/isbn/9780804172448-L.jpg", language: "english", totalChapters: 12, publishedAt: "2014-09-09", averageRating: 4.1, ratingsCount: 620000, popularityScore: 84 },

  { key: "brief-history", title: "A Brief History of Time", authorKey: "hawking", seriesKey: null, description: "Hawking explains cosmology, black holes, and the nature of time for general readers.", genres: ["biography", "science-fiction", "business"], coverImage: "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg", language: "english", totalChapters: 10, publishedAt: "1988-04-01", averageRating: 4.1, ratingsCount: 420000, popularityScore: 86 },
  { key: "anne-frank", title: "The Diary of a Young Girl", authorKey: "frank", seriesKey: null, description: "Anne Frank's diary of hiding from the Nazis in Amsterdam during World War II.", genres: ["biography", "historical", "drama"], coverImage: "https://covers.openlibrary.org/b/isbn/9780553296983-L.jpg", language: "english", totalChapters: 12, publishedAt: "1947-06-25", averageRating: 4.2, ratingsCount: 3400000, popularityScore: 92 },
  { key: "becoming", title: "Becoming", authorKey: "obama", seriesKey: null, description: "Michelle Obama's memoir of family, public life, and identity.", genres: ["biography", "drama", "historical"], coverImage: "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg", language: "english", totalChapters: 12, publishedAt: "2018-11-13", averageRating: 4.5, ratingsCount: 980000, popularityScore: 91 },
  { key: "atomic-habits", title: "Atomic Habits", authorKey: "clear", seriesKey: null, description: "A practical guide to building good habits and breaking bad ones with small changes.", genres: ["business", "biography", "comedy"], coverImage: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg", language: "english", totalChapters: 10, publishedAt: "2018-10-16", averageRating: 4.4, ratingsCount: 1100000, popularityScore: 94 },
  { key: "why-not-me", title: "Why Not Me?", authorKey: "kaling", seriesKey: null, description: "Mindy Kaling's funny essays on career, confidence, and Hollywood.", genres: ["comedy", "biography", "drama"], coverImage: "https://covers.openlibrary.org/b/isbn/9780804138154-L.jpg", language: "english", totalChapters: 10, publishedAt: "2015-09-15", averageRating: 3.9, ratingsCount: 280000, popularityScore: 78 },
  { key: "bossypants", title: "Bossypants", authorKey: "fey", seriesKey: null, description: "Tina Fey's comedic memoir of writing, performing, and navigating comedy culture.", genres: ["comedy", "biography", "business"], coverImage: "https://covers.openlibrary.org/b/isbn/9780316056861-L.jpg", language: "english", totalChapters: 10, publishedAt: "2011-04-05", averageRating: 4.0, ratingsCount: 780000, popularityScore: 82 },

  { key: "pride", title: "Pride and Prejudice", authorKey: "austen", seriesKey: null, description: "Elizabeth Bennet and Mr. Darcy navigate misunderstandings and social expectations.", genres: ["romance", "drama", "comedy"], coverImage: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg", language: "english", totalChapters: 12, publishedAt: "1813-01-28", averageRating: 4.3, ratingsCount: 3900000, popularityScore: 93 },
  { key: "jane-eyre", title: "Jane Eyre", authorKey: "bronte", seriesKey: null, description: "An orphaned governess finds love and independence at Thornfield Hall.", genres: ["romance", "drama", "historical"], coverImage: "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg", language: "english", totalChapters: 12, publishedAt: "1847-10-16", averageRating: 4.2, ratingsCount: 2100000, popularityScore: 88 },
  { key: "mockingbird", title: "To Kill a Mockingbird", authorKey: "lee", seriesKey: null, description: "Scout Finch observes racial injustice and moral courage in the American South.", genres: ["drama", "historical", "young-adult"], coverImage: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg", language: "english", totalChapters: 12, publishedAt: "1960-07-11", averageRating: 4.4, ratingsCount: 5600000, popularityScore: 96 },

  { key: "matilda", title: "Matilda", authorKey: "dahl", seriesKey: null, description: "A gifted girl uses her intellect—and unexpected powers—against cruel adults.", genres: ["children", "comedy", "fantasy"], coverImage: "https://covers.openlibrary.org/b/isbn/9780142410370-L.jpg", language: "english", totalChapters: 12, publishedAt: "1988-10-01", averageRating: 4.3, ratingsCount: 900000, popularityScore: 87 },
  { key: "charlie", title: "Charlie and the Chocolate Factory", authorKey: "dahl", seriesKey: null, description: "Charlie Bucket wins a tour of Willy Wonka's extraordinary chocolate factory.", genres: ["children", "comedy", "adventure"], coverImage: "https://covers.openlibrary.org/b/isbn/9780142410318-L.jpg", language: "english", totalChapters: 12, publishedAt: "1964-01-17", averageRating: 4.2, ratingsCount: 850000, popularityScore: 86 },
  { key: "lorax", title: "The Lorax", authorKey: "seuss", seriesKey: null, description: "The Lorax speaks for the trees in a cautionary tale about greed and nature.", genres: ["children", "comedy", "drama"], coverImage: "https://covers.openlibrary.org/b/isbn/9780679889106-L.jpg", language: "english", totalChapters: 6, publishedAt: "1971-08-12", averageRating: 4.4, ratingsCount: 420000, popularityScore: 85 },
  { key: "cat-hat", title: "The Cat in the Hat", authorKey: "seuss", seriesKey: null, description: "A mischievous cat turns a rainy day upside down for two children.", genres: ["children", "comedy", "fantasy"], coverImage: "https://covers.openlibrary.org/b/isbn/9780394800011-L.jpg", language: "english", totalChapters: 6, publishedAt: "1957-03-12", averageRating: 4.2, ratingsCount: 500000, popularityScore: 84 },

  { key: "percy1", title: "The Lightning Thief", authorKey: "riordan", seriesKey: "percy", description: "Percy Jackson learns he is a demigod and must recover Zeus's stolen lightning bolt.", genres: ["young-adult", "adventure", "fantasy"], coverImage: "https://covers.openlibrary.org/b/isbn/9780786838653-L.jpg", language: "english", totalChapters: 12, publishedAt: "2005-06-28", averageRating: 4.3, ratingsCount: 2800000, popularityScore: 92 },
  { key: "percy2", title: "The Sea of Monsters", authorKey: "riordan", seriesKey: "percy", description: "Percy sails into the Sea of Monsters to save Camp Half-Blood.", genres: ["young-adult", "adventure", "action"], coverImage: "https://covers.openlibrary.org/b/isbn/9781423103349-L.jpg", language: "english", totalChapters: 12, publishedAt: "2006-04-01", averageRating: 4.2, ratingsCount: 1600000, popularityScore: 88 },

  { key: "animal-farm", title: "Animal Farm", authorKey: "orwell", seriesKey: null, description: "Farm animals overthrow humans only to face a new tyranny.", genres: ["drama", "historical", "comedy"], coverImage: "https://covers.openlibrary.org/b/isbn/9780451526342-L.jpg", language: "english", totalChapters: 10, publishedAt: "1945-08-17", averageRating: 4.0, ratingsCount: 3500000, popularityScore: 90 },
  { key: "rich-dad", title: "Rich Dad Poor Dad", authorKey: "kiyosaki", seriesKey: null, description: "Lessons contrasting two father figures on money, assets, and financial independence.", genres: ["business", "biography", "comedy"], coverImage: "https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg", language: "english", totalChapters: 10, publishedAt: "1997-04-01", averageRating: 4.1, ratingsCount: 650000, popularityScore: 85 },
  { key: "steve-jobs", title: "Steve Jobs", authorKey: "isaacson", seriesKey: null, description: "Walter Isaacson's landmark biography of Apple co-founder Steve Jobs.", genres: ["biography", "business", "historical"], coverImage: "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg", language: "english", totalChapters: 12, publishedAt: "2011-10-24", averageRating: 4.2, ratingsCount: 1200000, popularityScore: 89 },
  { key: "girl-train", title: "The Girl on the Train", authorKey: "hawkins", seriesKey: null, description: "A commuter becomes entangled in a missing-person case she watches from the train.", genres: ["thriller", "mystery", "crime"], coverImage: "https://covers.openlibrary.org/b/isbn/9781594634024-L.jpg", language: "english", totalChapters: 12, publishedAt: "2015-01-13", averageRating: 3.9, ratingsCount: 2500000, popularityScore: 90 },
  { key: "outliers", title: "Outliers", authorKey: "gladwell", seriesKey: null, description: "Malcolm Gladwell examines the hidden factors behind extraordinary success.", genres: ["business", "biography", "historical"], coverImage: "https://covers.openlibrary.org/b/isbn/9780316017930-L.jpg", language: "english", totalChapters: 10, publishedAt: "2008-11-18", averageRating: 4.1, ratingsCount: 780000, popularityScore: 86 },
];
